"""init

Revision ID: 32805289ee45
Revises: dd33cb03d01f
Create Date: 2023-05-08 23:05:36.407745

"""

# revision identifiers, used by Alembic.
revision = '32805289ee45'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
